demands/urls.py
# -*- coding: utf-8 -*-
#
# urls.py
# This file is part of Logram Website
#
# Copyright (C) 2009 - Denis Steckelmacher <steckdenis@logram-project.org>
#
# Logram Website is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Logram is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Logram; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA  02110-1301  USA
#
from django.conf.urls.defaults import *

urlpatterns = patterns('pyv4.demands.views',
    #routes "demands-...", ou "demands-" n'est pas mis
    (r'^1\.html$', 'index'),
    (r'^2-(?P<type_id>\d+)-(?P<status_id>\d+)-(?P<product_id>\d+)(?P<sort>[a-z+-]+)-(?P<page>\d+)\.html$', 'mlist'),
    (r'^3\.html$', 'updatefilter'),
    (r'^4-(?P<demand_id>\d+)-(?P<page>\d+)\.html$', 'view'),
    (r'^5-(?P<attachment_id>\d+)\.html$', 'viewattachment'),
    (r'^6-(?P<attachment_id>\d+)\.html$', 'downloadattachment'),
    (r'^7-(?P<demand_id>\d+)\.html$', 'addattachment'),
    (r'^8-(?P<demand_id>\d+)\.html$', 'handlerelated'),
    (r'^9-(?P<demand_id>\d+)\.html$', 'handleassignees'),
    (r'^10-(?P<type_id>\d+)-(?P<product_id>\d+)-(?P<component_id>\d+)\.html$', 'newdemand'),
    (r'^11-(?P<demand_id>\d+)\.html$', 'edit_demand'),
    (r'^12-(?P<type_id>\d+)-(?P<product_id>\d+)-(?P<component_id>\d+)-(?P<platform_id>\d+)\.html$', 'newdemand_step2'),
    (r'^13-(?P<demand_id>\d+)\.html$', 'change_product'),
    (r'^14-(?P<demand_id>\d+)-(?P<component_id>\d+)\.html$', 'setstep1'),
)

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
    # Example:
    # (r'^pyv4/', include('pyv4.foo.urls')),
    
    (r'^$', 'pyv4.general.views.index'),
    (r'^ajax-preview.html$', 'pyv4.general.views.ajax_preview'),
    (r'^ajax-preview-pastebin-(?P<format>.+)\.html$', 'pyv4.general.views.ajax_preview_pastebin'),
    (r'^forum\.html$', 'pyv4.forum.views.index'),
    (r'^wiki\.html$', 'pyv4.wiki.views.index'),
    (r'^downloads\.html$', 'pyv4.packages.views.index'),
    
    (r'^news-', include('pyv4.news.urls')),
    (r'^upload-', include('pyv4.upload.urls')),
    (r'^user-', include('pyv4.users.urls')),
    (r'^forum-', include('pyv4.forum.urls')),
    (r'^wiki-', include('pyv4.wiki.urls')),
    (r'^packages-', include('pyv4.packages.urls')),
    (r'^demand-', include('pyv4.demands.urls')),
    (r'^mp-', include('pyv4.mp.urls')),
    (r'^feeds/', include('pyv4.feeds.urls')),
    (r'^pastebin-', include('pyv4.pastebin.urls')),

    (r'^login\.html$', 'pyv4.general.views.login'),
    (r'^login-1\.html$', 'pyv4.general.views.login_validate'),
    (r'^logout-(?P<user_id>\d+)\.html$', 'pyv4.general.views.logout'),
    (r'^register\.html$', 'pyv4.general.views.register'),
    (r'^search-(?P<page>\d+)\.html$', 'pyv4.general.views.search'),
    (r'^captcha.png$', 'pyv4.general.captcha.captcha'),
    (r'^devcorner.html$', 'pyv4.general.views.devcorner'),
                       
    (r'^i18n/', include('django.conf.urls.i18n')),
    
    (r'^style/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STYLE_ROOT}),
    (r'^files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

demands/models.py
# -*- coding: utf-8 -*-
#
# models.py
# This file is part of Logram Website
#
# Copyright (C) 2009 - Denis Steckelmacher <steckdenis@logram-project.org>
#
# Logram Website is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Logram is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Logram; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA  02110-1301  USA
#
from django.db import models
from django.contrib.auth.models import Group
from django.utils.translation import gettext_lazy as _
from django.utils.encoding import force_unicode

from pyv4.general.models import Profile
from pyv4.forum.models import Topic
from pyv4.packages.models import Arch

ASSIGNEE_TYPE = (
    (0, _('Utilisateur inscrit')),
    (1, _('Adresse e-mail')),
    (2, _('Url sur un autre bugtracker')),
)

RELATION_TYPE = (
    (0, _('La demande principale depend de la secondaire')),
    (1, _('Les demandes principales et secondaires sont liees')),
    (2, _('Les demandes principales et secondaires sont des duplicatas')),
)

class Type(models.Model):
    name = models.CharField(_('Nom'), max_length=200)
    description = models.TextField(_('Description'))
    color = models.CharField(_('Couleur'), max_length=6)
    icon = models.ImageField(_('Icône'), upload_to='uploads/%Y/%m/%d/%H%M%S')
    
    def color_vector(self):
        s = self.color
        r = int(s[0:2], 16)
        g = int(s[2:4], 16)
        b = int(s[4:6], 16)
        
        return (r, g, b)
        
    def vector_color(self, vec):
        return '%2X%2X%2X' % vec
        
    def neg_color(self, vec, amount):
        r = int(float(255 - vec[0]) * amount)
        g = int(float(255 - vec[1]) * amount)
        b = int(float(255 - vec[2]) * amount)
        
        return (r, g, b)
        
    def lightcolor(self):
        vec = self.color_vector()
        vec2 = self.neg_color(vec, 0.7)
        
        r = vec[0] + vec2[0]
        g = vec[1] + vec2[1]
        b = vec[2] + vec2[2]
        
        return self.vector_color((r, g, b))
        
    def darkcolor(self):
        vec = self.color_vector()
        vec2 = self.neg_color(vec, 0.5)
        
        r = vec[0] - vec2[0]
        g = vec[1] - vec2[1]
        b = vec[2] - vec2[2]
        
        return self.vector_color((r, g, b))
        
    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('Type')
        verbose_name_plural = _('Types')
    
class Status(models.Model):
    name = models.CharField(_('Nom'), max_length=200)
    description = models.TextField(_('Description'))
    closed = models.BooleanField(_('Demande fermée'))
    default = models.BooleanField(_('Type par défaut'))
    resolved = models.BooleanField(_('Demande résolue'))

    def __unicode__(self):
        return force_unicode(self.name)

    class Meta:
        verbose_name = _('Status')
        verbose_name_plural = _('Status')

class Product(models.Model):
    name = models.CharField(_('Nom'), max_length=64)
    title = models.CharField(_('Titre'), max_length=200)
    description = models.TextField(_('Description'))
    
    def __unicode__(self):
        return self.title
        
    class Meta:
        verbose_name = _('Produit')
        verbose_name_plural = _('Produits')
        
class Component(models.Model):
    name = models.CharField(_('Nom'), max_length=200)
    description = models.TextField(_('Description'))
    product = models.ForeignKey(Product, verbose_name=_('Produit'))
    
    def __unicode__(self):
        return self.name
        
    class Meta:
        verbose_name = _('Composant')
        verbose_name_plural = _('Composants')
        
class DefaultAssignee(models.Model):
    type = models.IntegerField(_('Type'), choices=ASSIGNEE_TYPE)
    user = models.ForeignKey(Profile, verbose_name=_('Utilisateur'), blank=True, null=True)
    value = models.CharField(_('Url ou adresse e-mail'), max_length=256)
    product = models.ForeignKey(Product, verbose_name=_('Produit'))
    
    def __unicode__(self):
        if self.type == 0:
            return self.user.uname
        else:
            return self.value
            
    class Meta:
        verbose_name = _('CC par defaut')
        verbose_name_plural = _('CC par defaut')

class ProductVersion(models.Model):
    name = models.CharField(_('Texte de la version'), max_length=64)
    product = models.ForeignKey(Product, verbose_name=_('Produit'))
    
    old = models.BooleanField(_('Version périmée'))
    future = models.BooleanField(_('Version future'))
    
    def __unicode__(self):
        return self.name
        
    class Meta:
        verbose_name = _('Version (produit)')
        verbose_name_plural = _('Versions (produit)')
        
class Platform(models.Model):
    name = models.CharField(_('Nom'), max_length=64)
    
    def __unicode__(self):
        return self.name
        
    class Meta:
        verbose_name = _('Plateforme')
        verbose_name_plural = _('Plateformes')
        
class PlatformVersion(models.Model):
    name = models.CharField(_('Texte de la version'), max_length=64)
    platform = models.ForeignKey(Platform, verbose_name=_('Plateforme'))
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        verbose_name = _('Version (plateforme)')
        verbose_name_plural = _('Version (plateforme)')
        
class Priority(models.Model):
    name = models.CharField(_('Nom'), max_length=200)
    description = models.TextField(_('Description'))
    priority = models.IntegerField(_('Pourcentage de priorité'))
    default = models.BooleanField(_('Priorité par défaut'))

    def red(self):
        # Niveau de rouge de la couleur
        r = self.priority - 50
        if r < 0: return 0

        # 0 < r <= 50, passer à l'échelle 0 < r <= 256
        return r * 256 / 50

    def blue(self):
        # Niveau de bleu de la couleur
        r = 50 - self.priority
        if r > 50 or r < 0: return 0

        # 0 < r <= 50, passer à l'échelle 0 < r <= 256
        return r * 256 / 50

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('Priorite')
        verbose_name_plural = _('Priorites')
        
class Demand(models.Model):
    title = models.CharField(_('Titre'), max_length=200)
    content = models.TextField(_('Contenu'))
    done = models.IntegerField(_('Pourcentage complété'))
    reporter = models.ForeignKey(Profile, verbose_name=_('Auteur'))
    type = models.ForeignKey(Type, verbose_name=_('Type de demande'))
    topic = models.ForeignKey(Topic, verbose_name=_('Sujet'))
    
    created_at = models.DateTimeField(_('Date de création'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Date de mise à jour'), auto_now=True)
    
    product = models.ForeignKey(Product, verbose_name=_('Produit'))
    component = models.ForeignKey(Component, verbose_name=_('Composant'))
    product_version = models.ForeignKey(ProductVersion, verbose_name=_('Version du produit'))
    fixed_in = models.ForeignKey(ProductVersion, blank=True, null=True, related_name='fixes', verbose_name=_('Fixé dans la version'))
    
    platform = models.ForeignKey(Platform, verbose_name=_('Plateforme'))
    platform_version = models.ForeignKey(PlatformVersion, verbose_name=_('Version de la plateforme'))
    
    architecture = models.ForeignKey(Arch, verbose_name=_('Architecture'))
    status = models.ForeignKey(Status, verbose_name=_('Status'))
    priority = models.ForeignKey(Priority, verbose_name=_('Priorité'))
    
    def __unicode__(self):
        return self.title
        
    class Meta:
        verbose_name = _('Demande')
        verbose_name_plural = _('Demandes')
        
class Relation(models.Model):
    type = models.IntegerField(_('Type'), choices=RELATION_TYPE)
    maindemand = models.ForeignKey(Demand, verbose_name=_('Demande principale'), related_name='relations_as_main')
    subdemand = models.ForeignKey(Demand, verbose_name=_('Sous-demande'), related_name='relations_as_sub')
    
    def __unicode__(self):
        return RELATION_TYPE[self.type][1] + ': ' + self.maindemand.title + ' > ' + self.subdemand.title
        
    class Meta:
        verbose_name = _('Relation')
        verbose_name_plural = _('Relations')
        
class Attachment(models.Model):
    author = models.ForeignKey(Profile, verbose_name=_('Auteur'))
    url = models.FileField(_('Fichier à joindre'), upload_to='uploads/%Y/%m/%d/%H%M%S')
    mimetype = models.CharField(_('Type MIME'), max_length=64)
    description = models.CharField(_('Description'), max_length=200)
    demand = models.ForeignKey(Demand, verbose_name=_('Demande'))
    invalidated = models.BooleanField(_('Invalidé'))
    
    def __unicode__(self):
        return self.description
        
    class Meta:
        verbose_name = _('Attachement')
        verbose_name_plural = _('Attachements')
        
class Assignee(models.Model):
    type = models.IntegerField(_('Type'), choices=ASSIGNEE_TYPE)
    user = models.ForeignKey(Profile, verbose_name=_('Utilisateur'), blank=True, null=True)
    value = models.CharField(_('Url ou adresse e-mail'), max_length=256)
    demand = models.ForeignKey(Demand, verbose_name=_('Demande'))
    default = models.BooleanField(_('Assigné par défaut'))
    
    def __unicode__(self):
        if self.type == 0:
            return self.user.uname
        else:
            return self.value
            
    class Meta:
        verbose_name = _('Assignee')
        verbose_name_plural = _('Assignees')

demands/forms.py
# -*- coding: utf-8 -*-
#
# forms.py
# This file is part of Logram Website
#
# Copyright (C) 2010 - Denis Steckelmacher <steckdenis@logram-project.org>
#
# Logram Website is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Logram is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Logram; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA  02110-1301  USA
#
from django import forms
from django.utils.translation import gettext_lazy as _

from pyv4.demands.models import Attachment

class AddAttachmentForm(forms.ModelForm):
    class Meta:
        model = Attachment
        fields = ('url', 'mimetype', 'description')

templates/demands/base.html
{% extends "global/base.html" %}
{% load i18n %}

{% block Demandes %}class="actif"{% endblock %}

{% block menu %}
{% endblock %}

{% block FAriane %}{{ block.super }} &raquo; 
    <a href="demand-1.html">
        {% trans "Demandes" %}
    </a>
{% endblock %}

templates/demands/list.html
{% extends "demands/base.html" %}
{% load i18n %}
{% load general_tags %}

{% block title %}
    {% if product %}
        {% trans product.title %}
    {% else %}
        {% trans type.name %}
    {% endif %}
{% endblock %}

{% block FAriane %}{{ block.super }} &raquo;
    {% if product %}
        {% trans product.title %}
    {% else %}
        {% trans type.name %}
    {% endif %}
{% endblock %}

{% block body %}
    <h1>
        {% if product %}
            {% trans product.title %}
        {% else %}
            {% trans type.name %}
        {% endif %}
    </h1>

    {% if product %}
        <p>
            {% blocktrans with product.title|translate as product %}
                Cette page est le centre de la gestion du projet «{{ product }}». Elle vous permet de filtrer ses bugs ou d'en ajouter directement de nouveaux.
            {% endblocktrans %}
        </p>
        
        <p>
            {{ product.description|translate|lcode }}
        </p>
        
        <h2>{% trans "Composants de ce produit" %}</h2>
        
        <dl>
            {% for component in product.component_set.all %}
                <dt><strong>{{ component.name }}</strong> (<a href="demand-10-0-{{ product.id }}-{{ component.id }}.html">{% trans "Soumettre une demande" %}</a>)</dt>
                <dd>{{ component.description|translate|lcode }}</dd>
            {% endfor %}
        </dl>
        
        <h2>{% trans "Liste des demandes" %}</h2>
    {% else %}
        <p style="overflow: hidden;">
            <img src="/files/{{ type.icon }}" alt="{% trans type.name %}" style="float: left;" />
            {% blocktrans with type.name|translate as type %}
                Voici la liste des demandes du type <strong>{{ type }}</strong>. Des filtres et options de tri sont à votre disposition pour affiner votre recherche.
            {% endblocktrans %}
        </p>
    {% endif %}

    <div id="forum_tools">
        <form action="demand-3.html" method="post">{% csrf_token %}
            <input type="hidden" name="product" value="{{ product_id }}" />
            <input type="hidden" name="page" value="{{ page }}" />
        
            <label for="type"><strong>{% trans "Type :" %}</strong></label>
            <select name="type" id="type">
                {% for t in types %}
                    <option value="{{ t.id }}" {% if t.id == type_id %}selected="selected"{% endif %}>{% trans t.name %}</option>
                {% endfor %}
            </select>
            
            <label for="status"><strong>{% trans "Status :" %}</strong></label>
            <select name="status" id="status">
                <option value="0">{% trans "Ne pas filtrer" %}</option>
                {% for s in status %}
                    <option value="{{ s.id }}" {% if s.id == status_id %}selected="selected"{% endif %}>{% trans s.name %}</option>
                {% endfor %}
            </select>
            
            <label for="order"><strong>{% trans "Trier par :" %}</strong></label>
            <select name="order" id="order">
                <option value="update" selected="selected">{% trans "Dernière modification" %}</option>
                <option value="date">{% trans "Date de création" %}</option>
                <option value="title">{% trans "Titre" %}</option>
                <option value="done">{% trans "Pourcentage effectué" %}</option>
                <option value="status">{% trans "Status" %}</option>
                <option value="priority">{% trans "Priorité" %}</option>
                <option value="author">{% trans "Auteur" %}</option>
                <option value="productversion">{% trans "Produit » Version" %}</option>
                <option value="productcomponent">{% trans "Produit » Composant" %}</option>
                <option value="platform">{% trans "Plateforme" %}</option>
                <option value="type">{% trans "Type" %}</option>
            </select>
            
            <input type="checkbox" name="desc" checked="true" />
            <label for="desc">{% trans "Descendant" %}</label>
            
            <input type="submit" />
        </form>
    </div>

    <style type="text/css">
        .demand_tbl tr th {
            background-color: #{{ type.lightcolor }} !important;
        }

        .demand_tbl, .demand_tbl td, .demand_tbl th {
            border-color: #{{ type.color }} !important;
        }
    </style>
    
    <table class="demand_tbl" style="text-align: center;">
        <tr>
            <th>{% trans "Auteur" %}</th>
            <th>{% trans "Titre" %}</th>
            {% if product %}
                <th>{% trans "Type" %}</th>
            {% else %}
                <th>{% trans "Produit" %}</th>
            {% endif %}
            <th>{% trans "Status" %}</th>
            <th>{% trans "Priorité" %}</th>
        </tr>
        {% for demand in demands %}
            <tr style="background-color: rgb({{ demand.priority.red }}, 128, {{ demand.priority.blue }});">
                <td>
                    {{ demand.reporter|color_pseudo }}
                </td>
                <td>
                    {% if demand.status.closed %}
                        <del>
                    {% endif %}
                    <a href="demand-4-{{ demand.id }}-1.html"
                       title="{% blocktrans with demand.created_at|format_date:request as created and demand.updated_at|format_date:request as updated %}Créée {{ created }}, mise à jour {{ updated }}{% endblocktrans %}">
                        {{ demand.title }}
                    </a>
                    {% if demand.status.closed %}
                        </del>
                    {% endif %}
                </td>
                <td>
                    {% if product %}
                        <a href="demand-2-{{ demand.type.id }}-{{ status_id }}-0{{ sort }}-{{ page }}.html">
                            {% trans demand.type.name %}
                        </a>
                    {% else %}
                        <a href="demand-2-0-{{ status_id }}-{{ demand.product.id }}{{ sort }}-{{ page }}.html"
                           title="{% blocktrans with demand.component.name as component and demand.product_version.name as version %}Composant {{ component }}, à la version {{ version }}{% endblocktrans %}">
                            {{ demand.product.title }}
                        </a>
                    {% endif %}
                </td>
                <td>
                    {% trans demand.status.name %}
                </td>
                <td style="color: rgb({{ demand.priority.red }}, 0, {{ demand.priority.blue }});">
                    {% trans demand.priority.name %}
                </td>
            </tr>
        {% endfor %}
    </table>
    
    <div class="pagination">
        {% for pg in list_pages %}
            <a href="demand-2-{{ type_id }}-{{ status_id }}-{{ product_id }}{{ sort }}-{{ pg }}.html">{{ pg }}</a>
        {% endfor %}
    </div>
{% endblock %}

templates/demands/view.html
{% extends "demands/base.html" %}
{% load i18n %}
{% load general_tags %}

{% block title %}{{ demand.title }}{% endblock %}

{% block FAriane %}{{ block.super }} &raquo;
    <a href="demand-2-0-0-{{ demand.product_id }}-update-1.html">{% trans demand.product.title %}</a> &raquo;
    <a href="demand-2-{{ demand.type_id }}-0-{{ demand.product_id }}-update-1.html">{% trans demand.type.name %}</a> &raquo;
    {{ demand.title }}
{% endblock %}

{% block body %}
    <h1>{{ demand.title }}</h1>
    
    <div id="demand_pane" style="background-color: #{{ demand.type.lightcolor }}; border-color: #{{ demand.type.darkcolor }};">
        <div id="news_infos">
            {{ demand.created_at|format_date:request }}
            {% trans "par" %} {{ demand.reporter|color_pseudo }},
            <a href="#comments">{% blocktrans with topic.num_posts as posts %}{{ posts }} commentaires{% endblocktrans %}</a>
        </div>
        
        <div id="demand_content_right">
            <ul>
                <li>
                    <strong>{% trans "% Réalisé :" %}</strong>
                    <div class="bar">
                        <div class="bar_bar" style="width: {{ demand.done }}%;">
                            {{ demand.done }}%
                        </div>
                    </div>
                </li>
                <li>
                    <strong>{% trans "Assigné à :" %}</strong>
                    <ul>
                        {% for assignee in assignees %}
                            <li>
                                {% if assignee.type == 0 %}
                                    {{ assignee.user|color_pseudo }}
                                {% else %}
                                    {% if assignee.type == 1 %}
                                        {{ assignee.value|obfuscate }}
                                    {% else %}
                                        <a href="{{ assignee.value }}">{{ assignee.value }}</a>
                                    {% endif %}
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                
                {% regroup relations by type_title as type_list %}
                
                {% for type in type_list %}
                    <li>
                        <strong>{{ type.grouper }}</strong>
                        <ul>
                            {% for rel in type.list %}
                                <li>
                                    {% if rel.item.status.closed %}
                                        <del>
                                            <a href="demand-4-{{ rel.item.id }}-1.html">{{ rel.item.title }}</a>
                                        </del>
                                    {% else %}
                                        <a href="demand-4-{{ rel.item.id }}-1.html">{{ rel.item.title }}</a>
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        </div>
        
        <div id="demand_content_left">
            <ul>
                <li>
                    {% blocktrans with demand.id as id %}
                        Demande n° <strong>{{ id }}</strong>
                    {% endblocktrans %}
                </li>
                <li>
                    <strong>{% trans "Status :" %}</strong> {% trans demand.status.name %}
                </li>
                <li>
                    <strong>{% trans "Priorité :" %}</strong>
                    <span
                        title="{% trans demand.priority.description %}"
                        style="color: rgb({{ demand.priority.red }}, 0, {{ demand.priority.blue }});">
                            {% trans demand.priority.name %}
                    </span>
                </li>
                <li>
                    <strong>{% trans "Produit :" %}</strong>
                    <a href="demand-2-0-0-{{ demand.product_id }}-update-1.html">{% trans demand.product.title %}</a> &raquo;
                    {{ demand.component.name }}
                </li>
                <li>
                    <strong>{% trans "Version :" %}</strong>
                    {{ demand.product_version.name }}
                </li>
                <li>
                    <strong>{% trans "Fixé dans la version :" %}</strong>
                    {% if demand.fixed_in %}
                        {{ demand.fixed_in.name }}
                    {% else %}
                        <em>{% trans "Indéfini" %}</em>
                    {% endif %}
                </li>
                <li>
                    <strong>{% trans "Plateforme :" %}</strong>
                    {{ demand.platform.name }} {{ demand.platform_version.name }}
                </li>
            </ul>
        </div>
        
        <table id="demand_attachments_list">
            <tr>
                <th>{% trans "Auteur" %}</th>
                <th>{% trans "Description" %}</th>
                <th>{% trans "Type MIME" %}</th>
            </tr>
            {% for a in attachments %}
                <tr>
                    <td>
                        {{ a.author|color_pseudo }}
                    </td>
                    <td>
                        {% if a.invalidated %}
                            <del><a href="demand-5-{{ a.id }}.html">{{ a.description }}</a></del>
                        {% else %}
                            <a href="demand-5-{{ a.id }}.html">{{ a.description }}</a>
                        {% endif %}
                        (<a href="demand-6-{{ a.id }}.html">{% trans "Télécharger" %}</a>)
                    </td>
                    <td style="text-align: center;">
                        {{ a.mimetype }}
                    </td>
                </tr>
            {% endfor %}
            {% if user.is_authenticated %}
                <tr>
                    <td colspan="3" style="text-align: center;">
                        <a href="demand-7-{{ demand.id }}.html">{% trans "Ajouter un attachement" %}</a>
                    </td>
                </tr>
            {% endif %}
        </table>
        
        <hr style="clear: right;" />
        
        <div>
            {{ demand.content|lcode }}
        </div>
        
        {% if perms.demands.change_demand %}
            <div style="text-align: right;">
                <a href="demand-11-{{ demand.id }}.html">{% trans "Éditer" %}</a> &bull;
                <a href="demand-8-{{ demand.id }}.html">{% trans "Gérer les demandes liées" %}</a> &bull;
                <a href="demand-9-{{ demand.id }}.html">{% trans "Gérer les assignations" %}</a>
            </div>
        {% endif %}
    </div>
    
    <div id="comments"></div>
    
    {% include "forum/posts_list.html" %}
{% endblock %}