urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
    # Example:
    # (r'^pyv4/', include('pyv4.foo.urls')),
    
    (r'^$', 'pyv4.general.views.index'),
    (r'^ajax-preview.html$', 'pyv4.general.views.ajax_preview'),
    (r'^ajax-preview-pastebin-(?P<format>.+)\.html$', 'pyv4.general.views.ajax_preview_pastebin'),
    (r'^forum\.html$', 'pyv4.forum.views.index'),
    (r'^wiki\.html$', 'pyv4.wiki.views.index'),
    (r'^downloads\.html$', 'pyv4.packages.views.index'),
    
    (r'^news-', include('pyv4.news.urls')),
    (r'^upload-', include('pyv4.upload.urls')),
    (r'^user-', include('pyv4.users.urls')),
    (r'^forum-', include('pyv4.forum.urls')),
    (r'^wiki-', include('pyv4.wiki.urls')),
    (r'^packages-', include('pyv4.packages.urls')),
    (r'^demand-', include('pyv4.demands.urls')),
    (r'^mp-', include('pyv4.mp.urls')),
    (r'^feeds/', include('pyv4.feeds.urls')),
    (r'^pastebin-', include('pyv4.pastebin.urls')),

    (r'^login\.html$', 'pyv4.general.views.login'),
    (r'^login-1\.html$', 'pyv4.general.views.login_validate'),
    (r'^logout-(?P<user_id>\d+)\.html$', 'pyv4.general.views.logout'),
    (r'^register\.html$', 'pyv4.general.views.register'),
    (r'^search-(?P<page>\d+)\.html$', 'pyv4.general.views.search'),
    (r'^captcha.png$', 'pyv4.general.captcha.captcha'),
    (r'^devcorner.html$', 'pyv4.general.views.devcorner'),
                       
    (r'^i18n/', include('django.conf.urls.i18n')),
    
    (r'^style/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STYLE_ROOT}),
    (r'^files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

wiki/urls.py
# -*- coding: utf-8 -*-
#
# urls.py
# This file is part of Logram Website
#
# Copyright (C) 2009 - Denis Steckelmacher <steckdenis@logram-project.org>
#
# Logram Website is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Logram is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Logram; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA  02110-1301  USA
#
from django.conf.urls.defaults import *

urlpatterns = patterns('pyv4.wiki.views',
    #routes "wiki-...", ou "wiki-" n'est pas mis
    (r'^1\.html$', 'randompage'),
    (r'^2-(?P<page>\d+)\.html$', 'changes'),
    (r'^3-(?P<page_id>\d+)-(?P<identifier>\d+)-(?P<slug>[a-z0-9_-]+)\.html$', 'edit'),
    (r'^4-(?P<page_id>\d+)\.html$', 'history'),
    (r'^5-(?P<page_id>\d+)\.html$', 'toggle_protect'),
    (r'^6-(?P<page_id>\d+)\.html$', 'toggle_private'),
    (r'^7-(?P<change_id>\d+)\.html$', 'pagedate'),
    (r'^8-(?P<change_id>\d+)\.html$', 'cancelchange'),
    
    # Page sans numéros, à la fin, cer elles récupèrent tout ce qui "reste"
    (r'^(?P<slug>[a-z0-9_-]+)\.html$', 'viewpage'),
    (r'^(?P<slug>[a-z0-9_-]+)\.(?P<lang>[a-z]{2})\.html$', 'viewpagelang'),
)

wiki/models.py
# -*- coding: utf-8 -*-
#
# models.py
# This file is part of Logram Website
#
# Copyright (C) 2009 - Denis Steckelmacher <steckdenis@logram-project.org>
#
# Logram Website is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Logram is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Logram; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA  02110-1301  USA
#
from django.db import models
from django.utils.translation import gettext_lazy as _

from pyv4.general.models import Profile

# Create your models here.
class Page(models.Model):
    title = models.CharField(_('Titre'), max_length=300)
    slug = models.CharField(_('Slug'), max_length=100)   # SlugField est unique, ce que nous ne voulons pas
    lang = models.CharField(_('Langue'), max_length=2)
    identifier = models.IntegerField(_('Identificateur'), blank=True, default=0)
    
    body = models.TextField(_('Contenu'))
    
    is_protected = models.BooleanField(_('Page protégée'))
    is_private = models.BooleanField(_('Page privée (accessible uniquement au staff)'))
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        verbose_name = _('Page')
        verbose_name_plural = _('Pages')
        
        permissions = (
            ('private_page', 'Set a page to private'),
            ('view_private_pages', 'View private pages'),
        )

class LogEntry(models.Model):
    page = models.ForeignKey(Page, verbose_name=_('Page'))
    
    comment = models.CharField(_('Commentaire'), max_length=300)
    body = models.TextField(_('Contenu à ce moment-là'))
    
    date = models.DateTimeField(_('Date de création'), auto_now_add=True)
    
    author_user = models.ForeignKey(Profile, verbose_name=_('Auteur (utilisateur)'), blank=True, null=True)
    author_ip = models.CharField(_('Auteur (adresse IP)'), max_length=15, blank=True, null=True)

wiki/views.py
# -*- coding: utf-8 -*-
#
# views.py
# This file is part of Logram Website
#
# Copyright (C) 2009 - Denis Steckelmacher <steckdenis@logram-project.org>
#
# Logram Website is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Logram is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Logram; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA  02110-1301  USA
#
from pyv4.wiki.models import *
from pyv4.wiki.forms import *
from pyv4.general.functions import *
from pyv4.general.templatetags.general_tags import format_date
from django.contrib import messages

from django.http import HttpResponseRedirect, Http404, HttpResponseNotFound
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.translation import gettext as _
from django.core.paginator import Paginator, EmptyPage, InvalidPage

import random

def index(request):
    return viewpagelang(request, 'index', 'auto')

def viewpage(request, slug):
    return viewpagelang(request, slug, 'auto')

def viewpagelang(request, slug, lang):
    # Afficher une page de wiki
    
    # Récupérer toutes les pages qui ont le slug demandé (ces pages ont des langues différentes)
    pages = Page.objects.filter(slug=slug)
    
    # Voir s'il y a au moins une page (len() fait une requête, c'est mieux, ça met en cache les résultats)
    if len(pages) == 0:
        # Pas de page, l'afficher
        return tpl('wiki/notfound.html',
            {'slug': slug}, request)
    
    # Si plus d'une page a ce slug, alors prendre celle qui a la langue de l'utilisateur.
    #    Si aucune n'a sa langue, prendre la version en anglais
    if len(pages) == 1:
        page = pages[0]
    else:
        lang_found = False
        
        for pg in pages:
            if pg.lang == lang:
                page = pg
                lang_found = True
                break
                
            elif request.LANGUAGE_CODE.startswith(pg.lang) and lang == 'auto':
                # Langue de l'utilisateur, et il n'en a pas spécifiée
                page = pg
                lang_found = True
                break
                
            elif pg.lang == 'en':
                page_en = pg
        
        if not lang_found:
            page = page_en
    
    # Si la page est privée, seul le staff y a accès
    if page.is_private and not request.user.has_perm('wiki.view_private_pages'):
        raise Http404
    
    # Trouver toutes les langues de la page (utiliser l'identificateur pour ça)
    langs = Page.objects \
        .only('lang', 'slug') \
        .filter(identifier=page.identifier)
    
    # Rendre la template
    return tpl('wiki/show.html', 
        {'page': page,
         'in_discover': slug.startswith('discover'),
         'langs': langs}, request)

@login_required
def edit(request, page_id, identifier, slug):
    # Créer une nouvelle page
    page_id = int(page_id)
    identifier = int(identifier)
    
    upl = False
    captcha_string = ''
    
    #            | zéro          | page_id
    # zéro       | nouvelle page | édition d'une page
    # identifier | POST new page | traduction d'une page 
    
    if request.method == 'POST':
        pbody = request.POST['body']
        page = False
        
        if page_id == 0 or identifier != 0:
            # Nouvelle page
            if not request.user.has_perm('wiki.add_page'):
                raise Http404
            
            form = NewForm(request.POST)
            
            if form.is_valid():
                if identifier != 0:
                    slug = slugify(form.cleaned_data['title'])
                
                page = Page(title=form.cleaned_data['title'],
                            slug=slug,
                            lang=form.cleaned_data['lang'],
                            body=request.POST['body'],
                            is_protected=False,
                            is_private=False)
                
                if identifier != 0:
                    page.identifier = identifier
                else:
                    page.save()
                    page.identifier = page.id
                
                page.save()
                
                # On a fini
                if not request.user.is_anonymous():
                    messages.add_message(request, messages.INFO, _(u'Page créée avec succès'))
                    
                return HttpResponseRedirect('wiki-%s.%s.html' % (slug, form.cleaned_data['lang']))
        else:
            page = get_object_or_404(Page, pk=page_id)
            lang = page.lang
            
            # Vérifier que la page n'est ni privée ni protégée
            if page.is_protected and request.user.is_anonymous():
                raise Http404
            elif page.is_private and not request.user.has_perm('wiki.view_private_pages'):
                raise Http404
            
            form = EditForm(request.POST)
                
            can = True
            
            # Vérifier le captcha
            if request.user.is_anonymous():
                if request.POST['captcha'] != request.session.get('captcha_good_letters', ''):
                    can = False
                
            if form.is_valid() and can:
                previous_body = page.body
                
                page.title = form.cleaned_data['title']
                page.body = request.POST['body']
                page.save()
                
                # Créer un enregistrement dans le log
                if request.user.is_anonymous():
                    logentry = LogEntry(page=page, body=previous_body, author_ip=request.META.get('REMOTE_ADDR'), comment=form.cleaned_data['log'])
                    logentry.save()
                else:
                    logentry = LogEntry(page=page, body=previous_body, author_user=request.user.get_profile(), comment=form.cleaned_data['log'])
                    logentry.save()
                
                # On a fini
                if not request.user.is_anonymous():
                    messages.add_message(request, messages.INFO, _(u'Page éditée avec succès'))
                    
                return HttpResponseRedirect('wiki-%s.%s.html' % (slug, page.lang))
    else:
        if page_id != 0:
            page = get_object_or_404(Page, pk=page_id)
            pbody = page.body
            
            if not request.user.is_anonymous():
                upl = upload_url(request, D_TYPE_WIKI, 8*1024*1024, page.id, page.title)
            
            if identifier == 0:
                form = EditForm({'title': page.title})
            else:
                form = NewForm({'title': page.title, 'identifier': identifier})
        else:
            # L'utilisateur doit avoir le droit d'ajouter une page, pour éviter le spam
            if not request.user.has_perm('wiki.add_page'):
                raise Http404
            
            page = False
            pbody = ''
            
            form = NewForm({'identifier': identifier, 'lang': ''})
                
        # Captcha si l'utilisateur n'est pas authentifié
        if request.user.is_anonymous():
            possible_color_names = [
                _('rouges'),
                _('verts'),
                _('bleus'),
                _('noirs')
            ]
            possible_color_rgb = [
                'rgb(255, 0,   0)',
                'rgb(0,   255, 0)',
                'rgb(0,   0,   255)',
                'rgb(0,   0,   0)'
            ]
            index = random.randint(0, len(possible_color_rgb) - 1)
            
            request.session['captcha_good_color_rgb'] = possible_color_rgb[index]
            good_name = possible_color_names[index]
            
            captcha_string = _('Saissez les caractères <span style="color: %(color)s;">%(name)s</span> de l\'image ci-dessus') % \
            {
                'color': possible_color_rgb[index],
                'name': good_name
            }
                
    # Afficher le formulaire
    return tpl('wiki/edit.html',
            {'slug': slug,
             'create': page_id == 0,
             'translate': (identifier != 0 and page_id != 0),
             'page_id': page_id,
             'identifier': identifier,
             'upload_url': upl,
             'page': page,
             'body': pbody,
             'captcha_string': captcha_string,
             'form': form}, request)

def randompage(request):
    # Une page au hasard, dans la langue de l'utilisateur
    
    # Prendre une page
    pages = Page.objects \
        .filter(lang=request.LANGUAGE_CODE.split('-')[0], is_private=False) \
        .order_by('?')
    
    page = pages[0]
    
    # Trouver toutes les langues de la page (utiliser l'identificateur pour ça)
    langs = Page.objects \
        .only('lang', 'slug') \
        .filter(identifier=page.identifier)
    
    # Rendre la template
    return tpl('wiki/show.html', 
        {'page': page,
         'langs': langs}, request)

def changes(request, page):
    # Historique de tout le wiki
    page = int(page)
    
    # Récupérer tout l'historique du wiki
    changes = LogEntry.objects \
        .select_related('author_user', 'author_user', 'page') \
        .defer('body') \
        .filter(page__is_private=False) \
        .order_by('-date')
    
    # Paginer tout ça
    paginator = Paginator(changes, 20)        # 20 changements par page
    
    if page < 1:

templates/wiki/base.html
{% extends "global/base.html" %}
{% load i18n %}

{% block FAriane %}{{ block.super }} &raquo; <a href="wiki.html">{% trans "Wiki" %}</a>{% endblock %}


{# On n'est plus dans l'accueil, mais dans le wiki #}

{% block Wiki %}{% if in_discover %}class="actif"{% endif %}{% endblock %}
{% block Docs %}{% if not in_discover %}class="actif"{% endif %}{% endblock %}

{% block menu %}
    <h2>{% trans "Wiki" %}</h2>
    
    <ul>
        <li><a href="wiki.html">{% trans "Accueil du wiki" %}</a></li>
        <li><a href="wiki-1.html">{% trans "Une page au hasard" %}</a></li>
        <li><a href="wiki-2-1.html">{% trans "Changements" %}</a></li>
    </ul>
    
    <div class="separateur"></div>
{% endblock %}

templates/wiki/changes.html
{% extends "wiki/base.html" %}
{% load i18n %}
{% load general_tags %}

{% block title %}{{ page.title }} - {% trans "Historique" %}{% endblock %}

{% block FAriane %}{{ block.super }} &raquo; 
    {% if not page.ignore_breadcrumb %}
        <a href="wiki-{{ page.slug }}.{{ page.lang }}.html">
                {{ page.title }}
        </a>
        &raquo;
    {% endif %}
    {% trans "Historique" %}
{% endblock %}

{% block body %}
    <h1>{{ page.title }} - {% trans "Historique" %}</h1>
    
    <p>
        {% blocktrans %}
            Voici la liste des changements faits sur cette page. Vous pouvez en profiter pour regarder
            à quoi ressemblait une page à un moment donné. <strong>Attention</strong> tout de même, vérifiez
            bien pour quelle raison elle a été modifiée ensuite (images choquantes insérées, textes ebscènes, virus, etc).
        {% endblocktrans %}
    </p>
    
    <table>
        <tr>
            <th style="width: 120px;">{% trans "Auteur" %}</th>
            {% if global_changes %}
                <th>{% trans "Page" %}</th>
            {% endif %}
            <th style="width: 150px;">{% trans "Date" %}</th>
            <th>{% trans "Commentaire" %}</th>
            <th style="width: 200px;">{% trans "Actions" %}</th>
        </tr>
        {% for change in changes %}
            <tr>
                <td style="text-align:center;">
                    {% if change.author_user %}
                        {{ change.author_user|color_pseudo }}
                    {% else %}
                        {{ change.author_ip }}
                    {% endif %}
                </td>
                {% if global_changes %}
                    <td style="text-align:center;">
                        <a href="wiki-{{ change.page.slug }}.{{ change.page.lang }}.html">
                            {{ change.page.title }}
                        </a>
                        ({{ change.page.lang}})
                    </td>
                {% endif %}
                <td style="text-align:center;">
                    {{ change.date|format_date:request }}
                </td>
                <td>
                    {{ change.comment }}
                </td>
                <td style="text-align:center;">
                    <a href="wiki-7-{{ change.id }}.html">{% trans "Page à cette date" %}</a>
                    
                    {% if perms.wiki.change_page %}
                        &bull;
                        <a href="wiki-8-{{ change.id }}.html">{% trans "Défaire" %}</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
    
    {% if list_pages %}
        <div class="pagination">
            {% for pg in list_pages %}
                <a href="wiki-2-{{ pg }}.html">{{ pg }}</a>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

templates/wiki/edit.html
{% extends "wiki/base.html" %}
{% load i18n %}

{% block title %}
    {% if page %}
        {{ page.title }}
    {% else %}
        {% trans "Création d'une page" %}
    {% endif %}
{% endblock %}

{% block FAriane %}{{ block.super }} &raquo; 
    {% if page %}
        <a href="wiki-{{ page.slug }}.{{ page.lang }}.html">
            {{ page.title }}
        </a>
        &raquo;
        {% trans "Édition" %}
    {% else %}
        {% trans "Création d'une page" %}
    {% endif %}
{% endblock %}

{% block body %}
    <h1>
        {% if page %}
            {{ page.title }}
        {% else %}
            {% trans "Création d'une page" %}
        {% endif %}
    </h1>
    
    {% blocktrans %}
        <p>
            <strong>Conseils pour la rédaction :</strong> N'oubliez pas de vérifier votre mise en
            page en cliquand sur «Aperçu». Vérifiez également l'orthographe et la grammaire. Vos propos
            doivent être compréhensibles par un utilisateur moyen sans connaissances techniques, sauf
            si votre page est adressée à un public particulier (page de spécifications, page pour
            développeurs, etc).
        </p>
        
        <p>
            Le wiki est formaté en <a href="wiki-markdown.html">Markdown</a>. Si vous
            devez mettre des images, <a href="upload-1-0.html">envoyez-les ici</a>.
        </p>
        
        <p>
            <strong>Attention :</strong> Vérifiez que la page que vous cherchez n'existe pas dans une
            autre langue. Si c'est le cas, allez sur cette page, et cliquez sur «Traduire».
        </p>
        
        <p>
            <strong>Remarque :</strong> Si vous n'êtes pas connectés, votre adresse IP sera sauvegardée
            dans le <em>log</em>, et sera visible de tous les utilisateurs.
        </p>
    {% endblocktrans %}
    
    <form action="wiki-3-{{ page_id }}-{{ identifier }}-{{ slug }}.html" method="post">{% csrf_token %}
        <fieldset>
            <legend>{% trans "Page" %}</legend>
            
            <p>
                <ul class="forum_ul">
                    {{ form.as_ul }}
                </ul>
            </p>
            
            {% if request.user.is_anonymous %}
                <p style="text-align: center;">
                    <img src="/captcha.png" alt="CAPTCHA" /><br />
                    <label for="captcha">{{ captcha_string|safe }}</label>
                    <input type="text" name="captcha" id="captcha" />
                </p>
            {% endif %}
            
            {% include "global/lform.html" %}
        </fieldset>
    </form>
{% endblock %}

templates/wiki/notfound.html
{% extends "wiki/base.html" %}
{% load i18n %}

{% block title %}{% trans "Page de documentation non-trouvée" %}{% endblock %}

{% block FAriane %}{{ block.super }} &raquo; 
    {% trans "Page de documentation non-trouvée" %}
{% endblock %}

{% block body %}
    <h1>{% trans "Page de documentation non-trouvée" %}</h1>
    
    <p>
        {% blocktrans %}La page que vous recherchez, <strong>{{ slug }}</strong>, n'existe pas. Elle a peut-être
        été supprimée, renomée, ou vous vous êtes trompé dans son nom.{% endblocktrans %}
    </p>
        
    <p>
        {% if perms.wiki.add_page %}
            {% blocktrans %}Si vous pensez que cette page pourrait être utile à d'autres, vous pouvez
            <a href="wiki-3-0-0-{{ slug }}.html">la créer</a>. Si vous avez absolument besoin de l'information
            contenue dans cette page, vous pouvez toujours essayer la recherche dans le menu de
            gauche.{% endblocktrans %}
        {% else %}
            {% blocktrans %}Vous n'avez malheureusement pas le droit de créer cette page vous-même. Une des solutions est de s'inscrire, ou, si vous êtes déjà inscrit, de demander à pouvoir créer une page de wiki (ou signaler ce problème, le wiki devrait être ouvert à tous les membres).{% endblocktrans %}
        {% endif %}
        </p>
{% endblock %}

templates/wiki/show.html
{% extends "wiki/base.html" %}
{% load i18n %}
{% load general_tags %}

{% block title %}{{ page.title }}{% endblock %}

{% block FAriane %}{{ block.super }} &raquo; {{ page.title }} {% endblock %}

{% block body %}
    <h1>{{ page.title }}</h1>
    
    <div id="wiki_links">
        <a href="wiki-4-{{ page.id }}.html">{% trans "Historique" %}</a>
        
        {% if not user.is_anonymous %}
            &bull; <a href="wiki-3-{{ page.id }}-0-{{ page.slug }}.html">{% trans "Éditer" %}</a>
            &bull; <a href="wiki-3-{{ page.id }}-{{ page.identifier }}-{{ page.slug }}.html">{% trans "Traduire" %}</a>
        {% endif %}
        
        {% if perms.wiki.change_page %}
            &bull;
            <a href="wiki-5-{{ page.id }}.html">
                {% if not page.is_protected %}
                    {% trans "Protéger" %}
                {% else %}
                    {% trans "Déprotéger" %}
                {% endif %}
            </a>
        {% endif %}
        
        {% if perms.wiki.private_page %}
            &bull;
            <a href="wiki-6-{{ page.id }}.html">
                {% if not page.is_private %}
                    {% trans "Rendre privée" %}
                {% else %}
                    {% trans "Rendre publique" %}
                {% endif %}
            </a>
        {% endif %}
    </div>
    
    <div id="forum_tools" style="margin-top: 0px;">
        <strong>{% trans "Autres langues" %} :</strong>
        {% for lang in langs %}
            {% if not forloop.first %}
                &bull;
            {% endif %}
            
            {% if lang.lang != page.lang %}
                <a href="wiki-{{ lang.slug }}.{{ lang.lang }}.html">{{ lang.lang }}</a>
            {% else %}
                {{ lang.lang }}
            {% endif %}
        {% endfor %}
    </div>
    
    <div id="wiki_page">
        {{ page.body|lcode }}
    </div>
{% endblock %}