forum/urls.py
# -*- coding: utf-8 -*-
#
# urls.py
# This file is part of Logram Website
#
# Copyright (C) 2009 - Denis Steckelmacher <steckdenis@logram-project.org>
#
# Logram Website is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Logram is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Logram; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA  02110-1301  USA
#
from django.conf.urls.defaults import *

urlpatterns = patterns('pyv4.forum.views',
    #routes "forum-...", ou "forum-" n'est pas mis
    (r'^1-(?P<forum_id>\d+)-(?P<page>\d+)-[a-z0-9_-]+\.html$', 'viewforum'),
    (r'^2-(?P<topic_id>\d+)-(?P<page>\d+)-[a-z0-9_-]+\.html$', 'viewtopic'),
    (r'^3-(?P<topic_id>\d+)\.html$', 'post'),
    (r'^4-(?P<post_id>\d+)\.html$', 'edit'),
    (r'^5-(?P<post_id>\d+)\.html$', 'toggle_helped'),
    (r'^6-(?P<forum_id>\d+)\.html$', 'newtopic'),
    (r'^7-(?P<forum_id>\d+)-(?P<page>\d+)\.html$', 'unread'),
    (r'^8-(?P<forum_id>\d+)-(?P<page>\d+)\.html$', 'mytopics'),
    (r'^9-(?P<forum_id>\d+)-(?P<page>\d+)\.html$', 'visited'),
    (r'^10-(?P<forum_id>\d+)-(?P<page>\d+)\.html$', 'posted'),
    (r'^11-(?P<topic_id>\d+)\.html$', 'toggle_solve'),
    (r'^12-(?P<topic_id>\d+)\.html$', 'alert'),
    (r'^13-(?P<topic_id>\d+)\.html$', 'moderate'),
    (r'^14-(?P<alert_id>\d+)\.html$', 'rmalert'),
    (r'^15-(?P<topic_id>\d+)\.html$', 'addpoll'),
    (r'^16-(?P<poll_id>\d+)\.html$', 'vote'),
    (r'^17-(?P<topic_id>\d+)\.html$', 'toggle_watch'),
    (r'^18-(?P<poll_id>\d+)\.html$', 'view_votes'),
)

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
    # Example:
    # (r'^pyv4/', include('pyv4.foo.urls')),
    
    (r'^$', 'pyv4.general.views.index'),
    (r'^ajax-preview.html$', 'pyv4.general.views.ajax_preview'),
    (r'^ajax-preview-pastebin-(?P<format>.+)\.html$', 'pyv4.general.views.ajax_preview_pastebin'),
    (r'^forum\.html$', 'pyv4.forum.views.index'),
    (r'^wiki\.html$', 'pyv4.wiki.views.index'),
    (r'^downloads\.html$', 'pyv4.packages.views.index'),
    
    (r'^news-', include('pyv4.news.urls')),
    (r'^upload-', include('pyv4.upload.urls')),
    (r'^user-', include('pyv4.users.urls')),
    (r'^forum-', include('pyv4.forum.urls')),
    (r'^wiki-', include('pyv4.wiki.urls')),
    (r'^packages-', include('pyv4.packages.urls')),
    (r'^demand-', include('pyv4.demands.urls')),
    (r'^mp-', include('pyv4.mp.urls')),
    (r'^feeds/', include('pyv4.feeds.urls')),
    (r'^pastebin-', include('pyv4.pastebin.urls')),

    (r'^login\.html$', 'pyv4.general.views.login'),
    (r'^login-1\.html$', 'pyv4.general.views.login_validate'),
    (r'^logout-(?P<user_id>\d+)\.html$', 'pyv4.general.views.logout'),
    (r'^register\.html$', 'pyv4.general.views.register'),
    (r'^search-(?P<page>\d+)\.html$', 'pyv4.general.views.search'),
    (r'^captcha.png$', 'pyv4.general.captcha.captcha'),
    (r'^devcorner.html$', 'pyv4.general.views.devcorner'),
                       
    (r'^i18n/', include('django.conf.urls.i18n')),
    
    (r'^style/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STYLE_ROOT}),
    (r'^files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

forum/models.py
# -*- coding: utf-8 -*-
#
# models.py
# This file is part of Logram Website
#
# Copyright (C) 2009 - Denis Steckelmacher <steckdenis@logram-project.org>
#
# Logram Website is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Logram is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Logram; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA  02110-1301  USA
#
from django.db import models
from django.utils.translation import gettext_lazy as _

from pyv4.general.models import Profile
from pyv4.pastebin.models import Pastebin
from django.contrib.auth.models import User

TOPIC_PARENT_TYPE = (
    (0, _('Forum')),
    (1, _('News')),
    (2, _('Demande')),
    (3, _('Paquet')),
)

# Create your models here.
class Category(models.Model):
    name = models.CharField(_('Nom'), max_length=200)
    description = models.CharField(_('Description'), max_length=400)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        verbose_name = _('Categorie')
        verbose_name_plural = _('Categories')

class Forum(models.Model):
    category = models.ForeignKey(Category, verbose_name=_('Catégorie'))
    
    name = models.CharField(_('Nom en français'), max_length=200)
    description = models.CharField(_('Description en français'), max_length=400)
    
    num_topics = models.IntegerField(_('Nombre de sujets'))
    num_posts = models.IntegerField(_('Nombre de posts'))
    
    last_topic = models.ForeignKey('Topic', verbose_name=_('Dernier sujet dans lequel on posté'), related_name='f', blank=True, null=True)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        verbose_name = _('Forum')
        verbose_name_plural = _('Forum')

class Poll(models.Model):
    question = models.CharField(_('Question'), max_length=200)
    pub_date = models.DateTimeField(_('Date de publication'), auto_now=True)
    topic = models.ForeignKey('Topic', verbose_name=_('Sujet'), related_name='polls')
    
    def __unicode__(self):
        return self.question
        
    class Meta:
        verbose_name = _('Sondage')
        verbose_name_plural = _('Sondages')
        
        permissions = (
            ('poll_on_all_topics', 'Add a poll on all topics'),
        )
    
class Choice(models.Model):
    poll = models.ForeignKey(Poll, verbose_name=_('Sondage'))
    choice = models.CharField(_('Choix'), max_length=200)
    votes = models.IntegerField(_('Votes'))
    
    def __unicode__(self):
        return self.choice
        
    class Meta:
        verbose_name = _('Choix')
        verbose_name_plural = _('Choix')
        
class UserChoice(models.Model):
    user = models.ForeignKey(Profile, verbose_name=_('Utilisateur'))
    choice = models.ForeignKey(Choice, verbose_name=_('Choix'))
    
    def __unicode__(self):
        return u'Choix'
        
    class Meta:
        verbose_name = _('Choix d\'utilisateur')
        verbose_name_plural = _('Choix d\'utilisateurs')
        
class Topic(models.Model):
    parent_id = models.IntegerField(_('ID du parent (forum, news, etc)'))
    p_type = models.IntegerField(_('Type'), choices=TOPIC_PARENT_TYPE)
    author = models.ForeignKey(Profile, verbose_name=_('Auteur'), blank=True, null=True)
    lang = models.CharField(_('Code ISO de la langue'), max_length=2)
    
    title = models.CharField(_('Titre'), max_length=150)
    subtitle = models.CharField(_('Sous-titre'), max_length=200)
    
    last_post = models.ForeignKey('Post', verbose_name=_('Dernier message'), related_name='t', blank=True, null=True)
    last_post_page = models.IntegerField(_('Page du dernier post dans le sujet'))
    num_posts = models.IntegerField(_('Nombre de messages'))
    
    stick = models.BooleanField(_('Post-it'))
    closed = models.BooleanField(_('Fermé'))
    resolved = models.BooleanField(_('Résolu'))
    
    poll = models.ForeignKey(Poll, verbose_name=_('Sondage lié'), blank=True, null=True, related_name='tp')
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        verbose_name = _('Sujet')
        verbose_name_plural = _('Sujets')

class Post(models.Model):
    topic = models.ForeignKey(Topic, verbose_name=_('Sujet'))
    author = models.ForeignKey(Profile, verbose_name=_('Auteur'))
    
    has_helped = models.BooleanField(_('A aidé l\'auteur du sujet'))
    date_created = models.DateTimeField(_('Date de création'), auto_now_add=True)
    date_modified = models.DateTimeField(_('Date de dernière mise à jour'), auto_now=True)
    
    contents = models.TextField(_('Contenu'))
    
    def __unicode__(self):
        # On ne s'en sert pas, normalement
        return 'post'
    
    class Meta:
        verbose_name = _('Message')
        verbose_name_plural = _('Messages')
        
        permissions = (
            ('edit_all_posts', 'Edit all posts'),
        )

class History(models.Model):
    post = models.ForeignKey(Post, verbose_name=_('Post'))
    author = models.ForeignKey(Profile, verbose_name=_('Auteur'))
    
    date = models.DateTimeField(_('Date de création'), auto_now_add=True)
    comment = models.CharField(_('Commentaire'), max_length=200)
    
    def __unicode__(self):
        return self.comment
    
    class Meta:
        verbose_name = _('Historique de message')
        verbose_name_plural = _('Historiques de message')

class UserTopic(models.Model):
    topic = models.ForeignKey(Topic, verbose_name=_('Sujet'))
    user = models.ForeignKey(Profile, verbose_name=_('Utilisateur'))
    
    last_read_post_page = models.IntegerField(_('Page du dernier post lu'))
    last_read_post = models.ForeignKey(Post, verbose_name=_('Dernier message lu'))

class Bookmark(models.Model):
    topic = models.ForeignKey(Topic, verbose_name=_('Sujet'))
    user = models.ForeignKey(User, verbose_name=_('Utilisateur'))

class Alert(models.Model):
    topic = models.ForeignKey(Topic, verbose_name=_('Sujet'), blank=True, null=True)
    paste = models.ForeignKey(Pastebin, verbose_name=_('Paste'), related_name='paste', blank=True, null=True)
    author = models.ForeignKey(Profile, verbose_name=_('Auteur'))
    
    comment = models.CharField(_('Commentaire'), max_length=400)
    
    def __unicode__(self):
        return self.comment
    
    class Meta:
        verbose_name = _('Alerte')
        verbose_name_plural = _('Alertes')
        
        permissions = (
            ('view_alerts', 'View alerts'),
        )

forum/forms.py
# -*- coding: utf-8 -*-
#
# forms.py
# This file is part of Logram Website
#
# Copyright (C) 2009 - Denis Steckelmacher <steckdenis@logram-project.org>
#
# Logram Website is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Logram is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Logram; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA  02110-1301  USA
#
from django import forms
from django.utils.translation import gettext_lazy as _

class EditForm(forms.Form):
    log = forms.CharField(label=_('Commentaire d\'édition'), required=True, max_length=200)

class NewTopicForm(forms.Form):
    title = forms.CharField(label=_('Titre du sujet'), required=True, max_length=150)
    subtitle = forms.CharField(label=_('Sous-titre du sujet'), required=False, max_length=200)
    lang = forms.CharField(label=_('Code ISO de la langue'), required=True, max_length=2)

class EditTopicForm(EditForm, NewTopicForm):
    pass
    
class AlertForm(forms.Form):
    comment = forms.CharField(label=_('Raison de l\'alerte'), required=True, max_length=400)

class PollForm(forms.Form):
    question = forms.CharField(label=_('Question'), required=True, max_length=200)
    choices = forms.CharField(label=_('Choix'), required=True, widget=forms.Textarea(), help_text=_('Un choix par ligne'))
    
    def clean(self):
        if not hasattr(self, 'cleaned_data'):
            return
        
        # Vérifier que les entrées sont bonnes
        cleaned_data = self.cleaned_data
        cs = cleaned_data['choices']
        
        # Splitter les choix
        css = cs.split('\n')
        
        # Compter les choix valides
        count = 0
        
        for c in css:
            if len(c.strip()) != 0:
                count += 1
        
        if count < 2:
            raise forms.ValidationError(_('Il faut au moins deux questions non-nulles, séparées par des retours à la ligne'))
        
        if len(cleaned_data['question'].strip()) == 0:
            raise forms.ValidationError(_('La question ne peut pas être composée de caractères vides'))
        
        return cleaned_data

templates/forum/posts_list.html
{% load i18n %}
{% load general_tags %}
    
{% if not user.is_anonymous %}
    <div id="forum_tools">
        <strong>{% trans "Actions :" %}</strong>
        
        {% if topic.author_id == user.get_profile.id %}
            {% if topic.p_type == 0 %}
                {% if not topic.resolved %}
                    <a href="forum-11-{{ topic.id }}.html" class="forum_tool_link">{% trans "Mon problème est résolu" %}</a>
                {% else %}
                    <a href="forum-11-{{ topic.id }}.html" class="forum_tool_link">{% trans "Mon problème n'est plus résolu" %}</a>
                {% endif %}
            {% endif %}
            
            {% if not topic.poll_id and perms.forum.add_poll %}
                <a href="forum-15-{{ topic.id }}.html" class="forum_tool_link">
                    {% trans "Ajouter un sondage" %}
                </a>
            {% endif %}
        {% else %}
            {% if perms.forum.poll_on_all_topics and not topic.poll_id %}
                <a href="forum-15-{{ topic.id }}.html" class="forum_tool_link">
                    {% trans "Ajouter un sondage" %}
                </a>
            {% endif %}
        {% endif %}
        
        {% if perms.forum.add_alert %}
            <a href="forum-12-{{ topic.id }}.html" class="forum_tool_link">{% trans "Avertir les modérateurs" %}</a>
        {% endif %}
        
        {% if perms.forum.change_topic %}
            <form action="forum-13-{{ topic.id }}.html" method="post">{% csrf_token %}
                <strong>{% trans "Modération :" %}</strong>
                
                <select name="action" id="action">
                    <option value="lock">{% trans "Fermer" %}</option>
                    <option value="dlock">{% trans "Rouvrir" %}</option>
                    {% if topic.p_type == 0 %}
                        <option value="solve">{% trans "Résoudre" %}</option>
                        <option value="dsolve">{% trans "Dé-résoudre" %}</option>
                        <option value="stick">{% trans "Mettre en post-it" %}</option>
                        <option value="dstick">{% trans "Dé-postiter" %}</option>
                        <option value="move">{% trans "Déplacer dans ..." %}</option>
                    {% endif %}
                </select>
                
                {% if topic.p_type == 0 %}
                    {% trans "Si déplacement : forum" %}
                    
                    <select name="forum" id="forum">
                        {% for frm in forums %}
                            <option value="{{ frm.id }}">
                                {% trans frm.name %}
                            </option>
                        {% endfor %}
                    </select>
                {% endif %}
                
                <input type="submit" value="OK" />
                
                <a href="/admin/forum/topic/{{ topic.id }}/">{% trans "Avancé" %}</a>
            </form>
        {% endif %}
    </div>
{% endif %}

{% if poll %}
    <div class="forum_poll">
        {% include "forum/viewpoll.html" %}
    </div>
{% endif %}

<table>
    <tr>
        <th style="width: 150px;">{% trans "Auteur" %}</th>
        <th>{% trans "Message" %}</th>
    </tr>
    {% for post in posts %}
        <tr class="forum_post_header">
            <td style="text-align: center;">
                {{ post.author|color_pseudo }}
            </td>
            <td>
                <div style="float: right;">
                    {% if perms.forum.edit_all_posts %}
                        <a href="forum-4-{{ post.id }}.html">{% trans "Éditer" %}</a>
                    {% else %}
                        {% if post.author == user.get_profile %}
                            {% if perms.forum.change_post %}
                                <a href="forum-4-{{ post.id }}.html">{% trans "Éditer" %}</a>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                    {% if post.topic.author == user.get_profile %}
                        {% if not post.has_helped %}
                            &bull; <a href="forum-5-{{ post.id }}.html">{% trans "Ce message m'a aidé" %}</a>
                        {% else %}
                            &bull; <a href="forum-5-{{ post.id }}.html">{% trans "Ce message ne m'a pas aidé" %}</a>
                        {% endif %}
                    {% endif %}
                    {% if perms.forum.edit_all_posts %}
                        &bull; <a href="/admin/forum/post/{{ post.id }}/">{% trans "Admin" %}</a>
                    {% endif %}
                </div>
                
                <a href="#r{{ post.id }}" id="r{{ post.id }}">#</a>
                {{ post.date_created|format_date:request }}
            </td>
        </tr>
        <tr>
            <td style="text-align: center; vertical-align: top;">
                {% with post.author as profile %}
                    {% include "forum/authorpane.html" %}
                {% endwith %}
            </td>
            <td {% if post.has_helped %}class="forum_post_helped"{% endif %} style="vertical-align: top;">
                {% if post.has_helped %}
                    <span class="forum_post_helped_title">{% trans "Ce message a aidé l'auteur du sujet" %}</span>
                {% endif %}
                
                <div class="forum_post_contents">
                    {{ post.contents|lcode }}
                </div>
                
                {% if post.edits %}
                    <h4 class="forum_post_edits">{% trans "Éditions" %}</h4>
                    
                    <ul class="forum_post_edits_ul">
                        {% for edit in post.edits %}
                            <li>{{ edit.date|format_date:request }} {% trans "par" %} {{ edit.author|color_pseudo }} : {{ edit.comment }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                
                {% if post.author.sign %}
                    <div class="forum_post_sign">
                        {{ post.author.sign|lcode }}
                    </div>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</table>


<div class="pagination">
    {% for pg in list_pages %}
        {% if topic.p_type == 0 %}
            <a href="forum-2-{{ topic.id }}-{{ pg }}-{{ topic.title|slugify }}.html">{{ pg }}</a>
        {% else %}{% if topic.p_type == 1 %}
            <a href="news-2-{{ news.id }}-{{ pg }}-{{ news.title|slugify }}.html">{{ pg }}</a>
        {% else %}{% if topic.p_type == 2 %}
            <a href="demand-4-{{ demand.id }}-{{ pg }}.html">{{ pg }}</a>
        {% else %}{% if topic.p_type == 3 %}
            <a href="packages-9-{{ source.id }}-{{ pg }}-{{ list_p }}.html">{{ pg }}</a>
        {% endif %}{% endif %}{% endif %}{% endif %}
    {% endfor %}
</div>

{% if not request.user.is_anonymous %}
    <div id="forum_watch">
        {% if not watch %}
            <img src="{{ style }}/img/bookmark.png" style="vertical-align: middle;">
            <a href="forum-17-{{ topic.id }}.html">
                {% trans "Surveiller" %}
            </a>
        {% else %}
            <img src="{{ style }}/img/debookmark.png" style="vertical-align: middle;">
            <a href="forum-17-{{ topic.id }}.html">
                {% trans "Ne plus surveiller" %}
            </a>
        {% endif %}
    </div>
{% endif %}

{% if not topic.closed and perms.forum.add_post %}
    <form action="forum-3-{{ topic.id }}.html" method="post">{% csrf_token %}
        <fieldset>
            <legend>{% trans "Répondre" %}</legend>
            
            {% include "global/lform.html" %}
        </fieldset>
    </form>
{% endif %}

templates/forum/viewforum.html
{% extends "forum/base.html" %}
{% load i18n %}
{% load general_tags %}


{% block title %}
    {% if not isnt_a_forum %}
        {% trans forum.name %}
    {% else %}
        {# Quand la template est utilisée pour les derniers sujets, etc #}
        {{ title }}
    {% endif %}
{% endblock %}

{% block FAriane %}{{ block.super }}
    {% if forum.id %}
        &raquo; 
        {% if title %}
            <a href="forum-1-{{ forum.id }}-1-{{ forum.name|slugify }}.html">
                {% trans forum.name %}
            </a>
        {% else %}
            {% trans forum.name %}
        {% endif %}
    {% endif %}
    
    {% if title %}
        {# Quand la template est utilisée pour les derniers sujets, etc #}
        &raquo; {{ title }}
    {% endif %}
{% endblock %}

{% block body %}
    {% if not isnt_a_forum %}
        <h1>{% trans forum.name %}</h1>
        <h2 style="text-align: center;">{% trans forum.description %}</h2>
    {% else %}
        <h1>{{ title }}</h1>
    {% endif %}
    
    {% if not user.is_anonymous %}
        <div id="forum_tools">
            <strong>{% trans "Actions :" %}</strong>
            
            {% if not isnt_a_forum %}
                {% if perms.forum.add_topic %}
                    <a href="forum-6-{{ forum.id }}.html">{% trans "Nouveau sujet" %}</a> &bull;
                {% endif %}
            {% else %}
                {% if forum.id == 0 %}
                    <a href="forum.html">{% trans "Ne plus filtrer" %}</a> &bull;
                {% else %}
                    <a href="forum-1-{{ forum.id }}-1-{{ forum.name|slugify }}.html">{% trans "Ne plus filtrer" %}</a> &bull;
                {% endif %}
            {% endif %}
            
            {% if not on_unread_topics %}
                <a href="forum-7-{{ forum.id }}-1.html">{% trans "Sujets non-lus" %}</a> &bull;
            {% else %}
                {% trans "Sujets non-lus" %} &bull;
            {% endif %}
            {% if not on_my_topics %}
                <a href="forum-8-{{ forum.id }}-1.html">{% trans "Mes sujets" %}</a> &bull;
            {% else %}
                {% trans "Mes sujets" %} &bull;
            {% endif %}
            {% if not on_visited_topics %}
                <a href="forum-9-{{ forum.id }}-1.html">{% trans "Sujets visités" %}</a> &bull;
            {% else %}
                {% trans "Sujets visités" %} &bull;
            {% endif %}
            {% if not on_posted_topics %}
                <a href="forum-10-{{ forum.id }}-1.html">{% trans "Où j'ai posté" %}</a>
            {% else %}
                {% trans "Où j'ai posté" %}
            {% endif %}
        </div>
    {% endif %}
    
    <table>
        <tr>
            <th style="width: 100px;"></th>
            <th>{% trans "Sujet" %}</th>
            <th style="width: 60px;">{% trans "Pages" %}</th>
            <th style="width: 100px;">{% trans "Auteur" %}</th>
            <th style="width: 100px;">{% trans "Messages" %}</th>
            <th style="width: 180px;">{% trans "Dernier message" %}</th>
        </tr>
        {% for topic in topics %}
            <tr {% if topic.stick %} class="forum_sticky" {% endif %}>
                <td style="text-align: right">
                    {% if topic.stick %}
                        <img src="{{ style }}/img/postit.png" alt="S" title="{% trans "Post-it" %}" />
                    {% else %}
                        <img src="{{ style }}/img/empty.png" alt="-" />
                    {% endif %}
                    {% if topic.closed %}
                        <img src="{{ style }}/img/lock.png" alt="L" title="{% trans "Fermé" %}" />
                    {% else %}
                        <img src="{{ style }}/img/empty.png" alt="-" />
                    {% endif %}
                    {% if topic.resolved %}
                        <img src="{{ style }}/img/resolu.png" alt="R" title="{% trans "Résolu" %}" />
                    {% else %}
                        <img src="{{ style }}/img/empty.png" alt="-" />
                    {% endif %}
                    {% if topic.read %}
                        <img src="{{ style }}/img/forum_read.png" alt="-" title="{% trans "Lu" %}" />
                    {% else %}
                        <img src="{{ style }}/img/forum_unread.png" alt="N" title="{% trans "Non-lu" %}" />
                    {% endif %}
                </td>
                <td style="line-height: 14px;">
                    <div class="lang_flag">
                        <img src="{{ style }}/img/{{ topic.lang }}.png" alt="fr" />
                    </div>
                    {% if topic.last_read_post_id and not topic.read %}
                        <a href="forum-2-{{ topic.id }}-{{ topic.last_read_post_page }}-{{ topic.title|slugify }}.html#r{{ topic.last_read_post_id }}" style="float: left;">
                            <img src="{{ style }}/img/last_post_read.png" alt="{% trans "Dernier message lu" %}" title="{% trans "Dernier message lu" %}" />
                        </a>
                    {% endif %}
                    <a href="forum-2-{{ topic.id }}-1-{{ topic.title|slugify }}.html">{{ topic.title }}</a><br />
                    <span class="forum_subtitle">{{ topic.subtitle }}</span>
                </td>
                <td style="text-align: center;">
                    {% for page in topic.pages %}
                        <a href="forum-2-{{ topic.id }}-{{ page }}-{{ topic.title|slugify }}.html">{{ page }}</a>
                    {% endfor %}
                </td>
                <td style="text-align: center;">
                    {{ topic.author|color_pseudo }}
                </td>
                <td style="text-align: center;">
                    {{ topic.num_posts }}
                </td>
                <td style="text-align: center;">
                    {% if topic.last_post %}
                        {% trans "Par" %} {{ topic.last_post.author|color_pseudo }}
                        {{ topic.last_post.date_created|format_date:request }}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
    
    <div class="pagination">
        {% for pg in list_pages %}
            {% if not isnt_a_forum %}
                <a href="forum-1-{{ forum.id }}-{{ pg }}-{{ forum.name|slugify }}.html">{{ pg }}</a>
            {% else %}
                <a href="forum-{{ func }}-{{ forum.id }}-{{ pg }}.html">{{ pg }}</a>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}